# SonarCloud properties
# Documentation: https://docs.sonarsource.com/sonarcloud/advanced-setup/automatic-analysis/

# Path to sources
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/target/**,**/dist/**,**/build/**,**/mockServiceWorker.js,**/mockServiceWorker.ts,**/mocks/**,**/*.min.js
#sonar.inclusions=

# Path to tests
#sonar.tests=
#sonar.test.exclusions=
#sonar.test.inclusions=

# Source encoding
sonar.sourceEncoding=UTF-8

# Exclusions for copy-paste detection
#sonar.cpd.exclusions=
