wrapperVersion=3.3.4
distributionType=only-script
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.10.0/apache-maven-3.10.0-bin.zip
distributionSha256Sum=88654080c88a7d30e575f11f9f736a88528bf6b7037e22c95d3819f6d47f7f0e
