package uk.co.hogandhivecrafts.backend.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.Generated;
import org.hibernate.generator.EventType;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * Represents a file associated with a craft pattern in the Hog & Hive Crafts system.
 * <p>
 * A file can be any type of document or media (PDF, image, document) that is related to
 * a specific pattern. Each file is associated with exactly one pattern and contains metadata
 * such as display name, storage path, content type, and file size. A SHA-256 checksum
 * provides data integrity verification.
 * <p>
 * Timestamps (createdAt, updatedAt) are managed by the database.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
@Table(name = "files")
@ToString(onlyExplicitlyIncluded = true)
public class File {

    /**
     * Unique identifier for the file, generated by the database.
     */
    @Id
    @GeneratedValue
    @ToString.Include
    private UUID id;

    /**
     * The role or purpose of this file within the pattern (e.g., "instructions", "guide", "reference").
     * This is a required field.
     */
    @Column(nullable = false)
    @ToString.Include
    private String role;

    /**
     * Human-readable display name for the file (e.g., "Pattern Instructions" or "Size Chart").
     */
    @Column(name = "display_name")
    @ToString.Include
    private String displayName;

    /**
     * The storage path or location where the file is stored (e.g., S3 bucket path, file system path).
     * This is a required field.
     */
    @Column(name = "storage_path", nullable = false)
    @ToString.Include
    private String storagePath;

    /**
     * Optional description of the file contents or purpose.
     */
    @Column(name = "description")
    @ToString.Include
    private String description;

    /**
     * The MIME type of the file (e.g., "application/pdf", "image/png", "text/plain").
     */
    @Column(name = "content_type")
    @ToString.Include
    private String contentType;

    /**
     * The size of the file in bytes.
     */
    @Column(name = "size_bytes")
    @ToString.Include
    private Long sizeBytes;

    /**
     * SHA-256 checksum of the file for integrity verification.
     */
    @Column(name = "checksum_sha256")
    @ToString.Include
    private String checksumSha256;

    /**
     * Timestamp when this file was created. Automatically set by the database on insert.
     * This field is immutable after creation.
     */
    // insertable = false means that when saving a new user, created_at and updated_at are not included
    // This results in the database setting the fields automatically using now()
    @Column(name = "created_at", nullable = false, insertable = false, updatable = false)
    @Generated(event = EventType.INSERT)
    @ToString.Include
    private OffsetDateTime createdAt;

    /**
     * Timestamp when this file was last updated. Automatically maintained by the database
     * on both insert and update operations.
     */
    @Column(name = "updated_at", nullable = false, insertable = false)
    @Generated(event = {EventType.INSERT, EventType.UPDATE})
    @ToString.Include
    private OffsetDateTime updatedAt;

    /**
     * The pattern this file belongs to. This is a required relationship.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "pattern_id", nullable = false)
    private Pattern pattern;

    /**
     * Helper method to safely extract the pattern ID from the relationship without triggering
     * lazy initialization. Used for serialization.
     *
     * @return the ID of the associated pattern, or null if pattern is not set
     */
    // Safe debug helper
    @ToString.Include(name = "patternId")
    public UUID getPatternId() {
        return pattern != null ? pattern.getId() : null;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof File other)) return false;

        return id != null && id.equals(other.id);
    }
}