package uk.co.hogandhivecrafts.backend.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.Generated;
import org.hibernate.generator.EventType;
import uk.co.hogandhivecrafts.backend.model.CraftType;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.UUID;

/**
 * Represents a craft pattern in the Hog & Hive Crafts system.
 * <p>
 * A pattern contains detailed information about a craft project, including its name,
 * source, type, and associated notes. Each pattern belongs to a user and can have
 * multiple associated files (e.g., PDFs, images). The combination of user_id and name
 * must be unique to prevent duplicate patterns for the same user.
 * <p>
 * Timestamps (createdAt, updatedAt) are managed by the database.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
@Table(
        name = "patterns",
        uniqueConstraints = {
                @UniqueConstraint(name = "uq_patterns_user_id_name", columnNames = {"user_id", "name"})
        }
)
@ToString(onlyExplicitlyIncluded = true)
public class Pattern {

    /**
     * Unique identifier for the pattern, generated by the database.
     */
    @Id
    @GeneratedValue
    @ToString.Include
    @EqualsAndHashCode.Include
    private UUID id;

    /**
     * The name of the pattern. Required field that, combined with userId, must be unique.
     */
    @Column(name = "name", nullable = false)
    @ToString.Include
    private String name;

    /**
     * The original source or reference for this pattern (e.g., book title, website URL, etc).
     */
    @Column(name = "source")
    @ToString.Include
    private String source;

    /**
     * The type of craft this pattern is for (e.g., KNITTING, CROCHET, SEWING, etc).
     * This field is required.
     */
    @Column(name = "craft_type", nullable = false)
    @ToString.Include
    @Enumerated
    private CraftType craftType;

    /**
     * Additional notes or comments about the pattern.
     */
    @Column(name = "notes")
    @ToString.Include
    private String notes;

    /**
     * Timestamp when this pattern was created. Automatically set by the database on insert.
     * This field is immutable after creation.
     */
    // insertable = false means that when saving a pattern, created_at and updated_at are not included
    // This results in the database setting the fields automatically using now()
    @Column(name = "created_at", nullable = false, insertable = false, updatable = false)
    @Generated(event = EventType.INSERT)
    @ToString.Include
    private OffsetDateTime createdAt;

    /**
     * Timestamp when this pattern was last updated. Automatically maintained by the database
     * on both insert and update operations.
     */
    @Column(name = "updated_at", nullable = false, insertable = false)
    @Generated(event = {EventType.INSERT, EventType.UPDATE})
    @ToString.Include
    private OffsetDateTime updatedAt;

    /**
     * The user who owns this pattern. This is a required relationship.
     */
    // Relationships
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    @EqualsAndHashCode.Exclude
    private User user;

    /**
     * List of files associated with this pattern (e.g., PDFs, images, documents).
     * Cascade operations ensure files are deleted when the pattern is deleted.
     */
    @OneToMany(mappedBy = "pattern", cascade = CascadeType.ALL, orphanRemoval = true)
    @EqualsAndHashCode.Exclude
    private List<File> files;

    /**
     * Helper method to safely extract the user ID from the relationship without triggering
     * lazy initialization. Used for serialization and debugging.
     *
     * @return the ID of the owning user, or null if user is not set
     */
    // Safe debug helper (no recursion risk)
    @ToString.Include(name = "userId")
    public UUID getUserId() {
        return user != null ? user.getId() : null;
    }

    /**
     * Helper method to extract file IDs from the files collection.
     * Note: accessing a lazy {@code files} collection here will trigger initialization.
     *
     * @return a list of file IDs, or an empty list if no files are associated
     */
    @ToString.Include(name = "fileIds")
    public List<UUID> getFileIds() {
        return files != null ? files.stream().map(File::getId).toList() : List.of();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Pattern other)) return false;

        return id != null && id.equals(other.id);
    }
}