package uk.co.hogandhivecrafts.backend.entity;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.UUID;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import org.hibernate.annotations.Generated;
import org.hibernate.generator.EventType;

/**
 * Represents a user in the Hog & Hive Crafts system.
 *
 * <p>A user is the owner of craft patterns and can have multiple associated patterns.
 * User timestamps (createdAt, updatedAt) are managed by the database and automatically populated on
 * insert and update operations.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
@Table(name = "users")
@ToString(onlyExplicitlyIncluded = true)
public class User {

  /**
   * Unique identifier for the user, generated by the database.
   */
  @Id
  // Postgres generates the UUID, so no generation strategy needs to be specified
  @GeneratedValue
  @ToString.Include
  private UUID id;

  /**
   * The user's email address.
   */
  @Column(name = "email")
  @ToString.Include
  private String email;

  /**
   * The user's display name. This is required and cannot be null.
   */
  @Column(name = "display_name", nullable = false)
  @ToString.Include
  private String displayName;

  /**
   * URL to the user's avatar image.
   */
  @Column(name = "avatar_url")
  @ToString.Include
  private String avatarUrl;

  /**
   * Timestamp when this user was created. Automatically set by the database on insert. This field
   * is immutable after creation.
   */
  // insertable = false means that when saving a new user, created_at and updated_at are not
  // included. This results in the database setting the fields automatically using now()
  @Column(name = "created_at", nullable = false, insertable = false, updatable = false)
  @Generated(event = EventType.INSERT)
  @ToString.Include
  private OffsetDateTime createdAt;

  /**
   * Timestamp when this user was last updated. Automatically maintained by the database on both
   * insert and update operations.
   */
  @Column(name = "updated_at", nullable = false, insertable = false)
  @Generated(event = {EventType.INSERT, EventType.UPDATE})
  @ToString.Include
  private OffsetDateTime updatedAt;

  /**
   * List of patterns owned by this user. The relationship is managed on the Pattern side. Cascade
   * operations ensure patterns are deleted when the user is deleted.
   */
  // Relationships
  // Pattern owns the relationship, User just reflects it
  @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, orphanRemoval = true)
  private List<Pattern> patterns;

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof User other)) {
      return false;
    }
    return id != null && id.equals(other.id);
  }

  @Override
  public int hashCode() {
    return id != null ? id.hashCode() : 0;
  }
}
