app:
  cors:
    allowed-origins: []
spring:
  application:
    name: backend
  datasource:
    driverClassName: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate
